name: CICD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out GitHub repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.2

      - name: "Configure poetry"
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: "Install dependencies"
        run: |
          python -m poetry install

      # - name: "Test with pytest"
      #   run: |
      #     python -m poetry run python -m pytest -v tests

  release:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: "Check out GitHub repository"
        uses: actions/checkout@v3
        with:
          ref: main
          # token: ${{ secrets.ADMIN_GITHUB_PAT }}

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: "Semantic Release"
        run: |
          pip install python-semantic-release==7.28.1
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish --verbosity=DEBUG
