name: Semantic Release

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Check out GitHub repository"
        uses: actions/checkout@v3

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.2.2

      - name: "Configure Poetry"
        run: |
          poetry config virtualenvs.in-project true

      - name: "Install dependencies"
        run: |
          poetry install --with dev

      # - name: "Test with pytest"
      #   run: |
      #     python -m poetry run python -m pytest -v tests

  release:
    needs: build-and-test
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: "Check out GitHub repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_GITHUB_PAT }}

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: "Set up Poetry"
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.2.2

      - name: "Configure Poetry"
        run: |
          poetry config virtualenvs.in-project true

      - name: "Install dev dependencies"
        run: |
          poetry install --only dev

      - name: "Semantic Release"
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          semantic-release publish --verbosity=DEBUG
        env:
          GH_TOKEN: ${{ secrets.ADMIN_GITHUB_PAT }}
